[package]
name = "dl_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.5"
mnist = "0.6.0"
ndarray = "0.15.1"
onnxruntime = { version = "0.0.14", features = ["model-fetching"] }
rand = "0.8.5"
